[package]
name = "xgb-benchmark"
version = "0.1.0"
edition = "2024"

[dependencies]
xgboost-rs = { version = "0.3.0" }
ndarray = { version = "0.16.1", features = ["std"] }
ndarray-rand = "0.15"
rand = "0.9.1"
rand_distr = "0.5.1"
indicatif = "0.17"
